name: ci-cd
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  STACK_NAME_DEV: portfolio-cicd-dev
  SAM_BUCKET: portfolio-cicd-artifacts-mahsa-cicd-artifacts-20251030   # change this to a globally-unique bucket name

jobs:
  test_build_deploy_dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::108782059508:role/GitHubOIDC-Deploy-Dev   # replace with your Role ARN
          role-session-name: github-actions-dev

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM build
        run: sam build --use-container

      - name: Ensure artifacts bucket
        run: |
          aws s3 mb s3://${{ env.SAM_BUCKET }} 2>/dev/null || true

      - name: SAM deploy (dev)
        run: |
          sam deploy \
            --stack-name $STACK_NAME_DEV \
            --s3-bucket $SAM_BUCKET \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION \
            --no-fail-on-empty-changeset
